apiVersion: v1
kind: Service
metadata:
  name: llm-security-gateway-service
  namespace: llm-security-gateway
spec:
  type: NodePort
  selector:
    app: llm-security-gateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080